databases:
  - name: ogrpdb
    plan: free
    databaseName: ogrp
    user: ogrp

services:
  - type: web
    plan: free
    name: ogrp
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn Online_Grievance_Redressal_Portal.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ogrpdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4